
# Site settings
title: Random Musings of a Tyson's Mind
description: A starter site
baseurl: "/tysons-random-musings" # folder where your site lives, e.g. /web1-sp - needs to start with a slash
url: "https://hickst16.github.io" # the base hostname & protocol for your site, e.g. http://hostname.domain.com

# Build settings
markdown: kramdown

defaults:  
  # template for pages unless an alternative is specified
  - scope:
      path: ""
    values:
      layout: "default"
  
  # Author Settings
  author: Tyson Hicks
  about-author: Random posts concocted from my random mind. 
